version: '3.8'

services:
  db:
    image: postgres:13
    container_name: postgres_db
    env_file:
      - ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
 
 

  backend:
    build:
      context: ./backend
    container_name: backend
    depends_on:
      - db
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app

 
 

 
  stripe:
    image: stripe/stripe-cli:v1.21.2  
    container_name: stripe
    command: ["listen", "--forward-to", "http://backend:8000/api/payment/stripe_webhook"]
    depends_on:
      - backend
    env_file:
      - ./.env
   

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    volumes:
      - node_modules:/apps/frontend/node_modules
    depends_on:
      - backend

  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/build:/usr/share/nginx/html  
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend

volumes:
  node_modules:
  postgres_data: