# Generated by Django 4.1.5 on 2024-06-10 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_orderitem_note_orderitem_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='IP_Address',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
