# Generated by Django 4.1.5 on 2024-06-11 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_ip_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipping_Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to='files/images/Item/%Y/%m/%d/')),
                ('name', models.CharField(max_length=50)),
                ('shipping_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('work_days', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='shipping_country',
            name='shipping_price',
        ),
        migrations.AddField(
            model_name='shipping_country',
            name='Shipping',
            field=models.ManyToManyField(blank=True, to='orders.shipping_company'),
        ),
    ]
