# Generated by Django 4.1.5 on 2024-06-12 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_order_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='zip',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
