# Generated by Django 4.1.5 on 2024-06-12 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_order_shipping_order_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Shipping',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.shipping_company'),
        ),
    ]
