# Generated by Django 4.1.5 on 2024-06-12 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_order_shipping'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='apartment_address',
            new_name='neighborhood',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='zip',
            new_name='street',
        ),
    ]
