# Generated by Django 4.1.5 on 2024-06-12 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_rename_apartment_address_order_neighborhood_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='note',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
