# Generated by Django 4.1.5 on 2024-06-13 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_alter_order_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipping_company',
            name='discount_price',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
