# Generated by Django 4.1.5 on 2024-06-14 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_shipping_company_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='new',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='order',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
