# Generated by Django 4.1.5 on 2024-06-18 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_order_new_order_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='order',
            name='default',
        ),
    ]
