# Generated by Django 4.1.5 on 2024-06-18 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_remove_order_cart_remove_order_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('neighborhood', models.CharField(blank=True, max_length=100, null=True)),
                ('street', models.CharField(blank=True, max_length=100, null=True)),
                ('shipping_address', models.CharField(blank=True, max_length=500, null=True)),
                ('IP_Address', models.CharField(blank=True, max_length=20, null=True)),
                ('IP_country', models.CharField(blank=True, max_length=100, null=True)),
                ('IP_Region', models.CharField(blank=True, max_length=100, null=True)),
                ('IP_city', models.CharField(blank=True, max_length=100, null=True)),
                ('purchase_count', models.PositiveIntegerField(default=0)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.shipping_country')),
            ],
        ),
    ]
