# Generated by Django 4.1.5 on 2024-06-19 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_customers_session_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='governorate',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
