# Generated by Django 4.1.5 on 2024-06-20 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_remove_package_created_at_remove_package_updated_at_and_more'),
        ('orders', '0021_customers_governorate'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.package'),
        ),
    ]
