# Generated by Django 4.1.5 on 2024-06-22 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0023_alter_customers_purchase_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='IP_Region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.region'),
        ),
        migrations.AlterField(
            model_name='customers',
            name='IP_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.city'),
        ),
        migrations.AlterField(
            model_name='customers',
            name='IP_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.country'),
        ),
    ]
