# Generated by Django 4.1.5 on 2024-06-24 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0025_customers_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='IP_Address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='IP_Region',
        ),
        migrations.RemoveField(
            model_name='order',
            name='IP_city',
        ),
        migrations.RemoveField(
            model_name='order',
            name='IP_country',
        ),
        migrations.RemoveField(
            model_name='order',
            name='city',
        ),
        migrations.RemoveField(
            model_name='order',
            name='country',
        ),
        migrations.RemoveField(
            model_name='order',
            name='email',
        ),
        migrations.RemoveField(
            model_name='order',
            name='name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='neighborhood',
        ),
        migrations.RemoveField(
            model_name='order',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='street',
        ),
    ]
