# Generated by Django 4.1.5 on 2024-06-29 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0026_remove_order_ip_address_remove_order_ip_region_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingCompany_balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('final_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('shipping', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.shipping_company')),
            ],
        ),
    ]
