# Generated by Django 5.0.6 on 2024-07-01 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0027_shippingcompany_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingcompany_balance',
            name='added_amount',
            field=models.FloatField(default=0),
        ),
    ]
