# Generated by Django 5.0.6 on 2024-07-01 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0028_shippingcompany_balance_added_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='cost',
            field=models.IntegerField(default=0),
        ),
    ]
