# Generated by Django 5.0.6 on 2024-07-01 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0029_orderitem_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
