# Generated by Django 5.0.6 on 2024-07-01 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0031_orderitem_date_sold_orderitem_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DictionaryProductName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='name',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='dictionary',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='orders.dictionaryproductname'),
            preserve_default=False,
        ),
    ]
