# Generated by Django 5.0.6 on 2024-07-01 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0032_dictionaryproductname_remove_orderitem_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictionary',
            name='name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dictionaryproductname',
            name='name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
