# Generated by Django 5.0.6 on 2024-07-06 23:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0035_orderitem_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customers',
            name='order',
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.customers'),
        ),
    ]
