# Generated by Django 5.0.6 on 2024-07-07 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0036_remove_customers_order_order_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='session_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
