# Generated by Django 5.0.6 on 2024-07-09 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0038_order_invoice_number_alter_order_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tax_amount',
            field=models.IntegerField(default=0),
        ),
    ]
