# Generated by Django 4.2.13 on 2024-08-14 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0040_alter_orderitem_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipping_company',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='files/images/Item/%Y/%m/%d/'),
        ),
    ]
