# Generated by Django 4.1.5 on 2024-06-06 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_frequentlyasked_category_top_slider_mobile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='theme_type',
            field=models.CharField(blank=True, choices=[('themeone', 'ThemeOne'), ('themetwo', 'ThemeTwo'), ('themethree', 'ThemeThree')], default='', max_length=20, null=True),
        ),
    ]
