# Generated by Django 4.1.5 on 2024-06-08 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_is_active_note_product_note_help_bottom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='note_help',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
