# Generated by Django 4.1.5 on 2024-06-08 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_product_price1_product_price2_product_price3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='currency',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
