# Generated by Django 4.1.5 on 2024-06-08 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_product_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='default_option',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
