# Generated by Django 4.1.5 on 2024-06-08 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_product_subtitle_alter_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_side_one',
            field=models.FileField(blank=True, null=True, upload_to='files/images/side_one/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_side_two',
            field=models.FileField(blank=True, null=True, upload_to='files/images/side_one/%Y/%m/%d/'),
        ),
    ]
