# Generated by Django 4.1.5 on 2024-06-08 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_product_image_side_one_product_image_side_two'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
