# Generated by Django 4.1.5 on 2024-06-09 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_coupon_product_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='expiryDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
