# Generated by Django 4.1.5 on 2024-06-20 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_remove_product_keywords_remove_product_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='expiration_date_offer',
            field=models.DateField(blank=True, null=True),
        ),
    ]
