# Generated by Django 4.1.5 on 2024-06-21 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_alter_product_expiration_date_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='home_image',
            field=models.FileField(blank=True, null=True, upload_to='files/images/Item/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
