# Generated by Django 4.1.5 on 2024-06-22 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_moreinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('rate_number', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
