# Generated by Django 4.1.5 on 2024-06-22 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
    ]
