# Generated by Django 4.1.5 on 2024-06-26 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0030_alter_product_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image_product',
            name='name',
        ),
    ]
