# Generated by Django 4.1.5 on 2024-06-26 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0031_remove_image_product_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='theme_content_type',
        ),
        migrations.RemoveField(
            model_name='product',
            name='theme_id',
        ),
    ]
