# Generated by Django 4.1.5 on 2024-06-26 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0032_remove_product_theme_content_type_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ThemeOne',
        ),
        migrations.DeleteModel(
            name='ThemeThree',
        ),
        migrations.DeleteModel(
            name='ThemeTwo',
        ),
    ]
