# Generated by Django 4.2.13 on 2024-08-14 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0033_delete_themeone_delete_themethree_delete_themetwo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='home_image',
            field=models.ImageField(blank=True, null=True, upload_to='files/images/Item/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='category',
            name='top_slider_mobile',
            field=models.ImageField(blank=True, null=True, upload_to='files/images/Item/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='category',
            name='top_slider_web',
            field=models.ImageField(blank=True, null=True, upload_to='files/images/Item/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='image_product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='files/images/Item/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='moreinfo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='files/images/MoreInfo/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_side_one',
            field=models.ImageField(blank=True, null=True, upload_to='files/images/side_one/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_side_two',
            field=models.ImageField(blank=True, null=True, upload_to='files/images/side_one/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='images',
            field=models.ManyToManyField(blank=True, to='products.image_product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='top_slider_mobile',
            field=models.ImageField(blank=True, null=True, upload_to='files/images/Item/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='top_slider_web',
            field=models.ImageField(blank=True, null=True, upload_to='files/images/Item/%Y/%m/%d/'),
        ),
    ]
