# Generated by Django 4.1.5 on 2024-06-29 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_remove_package_package_type_package_description_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShippingCompany',
            new_name='ShippingCompany_balance',
        ),
        migrations.DeleteModel(
            name='Advertisement',
        ),
    ]
