# Generated by Django 4.1.5 on 2024-06-29 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0008_rename_shippingcompany_shippingcompany_balance_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShippingCompany_balance',
        ),
        migrations.AddField(
            model_name='monthlyadbudget',
            name='name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
