# Generated by Django 5.0.6 on 2024-07-03 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0011_alter_monthlyadbudget_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monthlyadbudget',
            old_name='amount',
            new_name='added_amount',
        ),
        migrations.AddField(
            model_name='monthlyadbudget',
            name='final_balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monthlyadbudget',
            name='initial_balance',
            field=models.IntegerField(default=0),
        ),
    ]
