# Generated by Django 4.2.13 on 2024-08-14 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0012_rename_amount_monthlyadbudget_added_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='files/images/Item/%Y/%m/%d/'),
        ),
    ]
