# Generated by Django 4.1.5 on 2024-06-04 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='IP_Address',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
