# Generated by Django 4.1.5 on 2024-06-05 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_note_cart_ip_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='notes',
            field=models.ManyToManyField(blank=True, to='cart.note'),
        ),
    ]
