# Generated by Django 4.1.5 on 2024-06-07 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_cartitem_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='notes',
            field=models.ManyToManyField(blank=True, null=True, to='cart.note'),
        ),
    ]
