# Generated by Django 4.1.5 on 2024-06-11 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_remove_cartitem_total_cart_shipping_cart_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='tax',
            field=models.IntegerField(default=0),
        ),
    ]
