# Generated by Django 4.2.13 on 2024-06-17 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_cart_tax'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='IP_Address',
        ),
    ]
