# Generated by Django 4.1.5 on 2024-06-22 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_remove_cart_ip_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='shipping',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='tax',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='total',
        ),
    ]
