# Generated by Django 4.2.13 on 2024-08-14 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0011_cart_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='notes',
            field=models.ManyToManyField(blank=True, to='cart.note'),
        ),
    ]
