# Generated by Django 4.1.5 on 2024-06-06 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='title',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='groupproduct',
            name='title',
            field=models.CharField(max_length=300),
        ),
    ]
