# Generated by Django 4.1.5 on 2024-06-06 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_deal_title_alter_groupproduct_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('link', models.CharField(max_length=300)),
                ('image', models.FileField(blank=True, null=True, upload_to='files/images/Item/%Y/%m/%d/')),
            ],
        ),
    ]
