# Generated by Django 4.1.5 on 2024-06-21 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupproduct',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
