# Generated by Django 4.1.5 on 2024-06-21 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_groupproduct_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupproduct',
            name='price',
            field=models.CharField(max_length=10),
        ),
    ]
