# Generated by Django 4.1.5 on 2024-06-23 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_groupproduct_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CategoryList',
        ),
        migrations.AlterField(
            model_name='groupproduct',
            name='price',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
