# Generated by Django 4.1.5 on 2024-06-24 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_delete_categorylist_alter_groupproduct_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='Map_Address',
        ),
        migrations.RemoveField(
            model_name='info',
            name='PHONE',
        ),
        migrations.RemoveField(
            model_name='info',
            name='keywords',
        ),
        migrations.RemoveField(
            model_name='info',
            name='linkedin',
        ),
        migrations.AddField(
            model_name='info',
            name='pixel_id',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
    ]
