# Generated by Django 4.1.5 on 2024-06-24 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_info_map_address_remove_info_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='pixel_id',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
