# Generated by Django 4.1.5 on 2024-06-24 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_info_pixel_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='offer_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
