# Generated by Django 4.1.5 on 2024-06-27 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_info_offer_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deal',
            name='big_deal',
        ),
    ]
