# Generated by Django 4.1.5 on 2024-06-29 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_remove_deal_big_deal'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='StripeFee',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=5),
        ),
    ]
