# Generated by Django 4.2.13 on 2024-08-14 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_info_stripefee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='FaviconIco',
            field=models.ImageField(blank=True, null=True, upload_to='files/images/FaviconIco/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='info',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='files/images/logo/%Y/%m/%d/'),
        ),
    ]
