# Generated by Django 4.2.13 on 2024-09-12 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_info_stripefee'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='TikTok',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='info',
            name='email',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
