# Generated by Django 4.1.5 on 2024-06-05 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='status',
        ),
        migrations.AddField(
            model_name='payment',
            name='paid',
            field=models.BooleanField(default=True),
        ),
    ]
