name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code from the repository
      - name: Check out the code
        uses: actions/checkout@v4

      # Step 2: Set up Docker Buildx, which is required for advanced Docker builds
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Step 3: Log in to Docker Hub using credentials stored in GitHub Secrets
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Step 4: Build and push the backend Docker image
      - name: Build and Push backend Docker image
        env:
          REPOSITORY: backend
          IMAGE_TAG: latest
        run: |
          # Build the Docker image for the backend service
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/$REPOSITORY:$IMAGE_TAG -f backend/Dockerfile backend/
          # Push the backend Docker image to Docker Hub
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/$REPOSITORY:$IMAGE_TAG

      # Step 5: Build and push the frontend Docker image
      - name: Build and Push frontend Docker image
        env:
          REPOSITORY: frontend
          IMAGE_TAG: latest
        run: |
          # Build the Docker image for the frontend service
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/$REPOSITORY:$IMAGE_TAG -f frontend/Dockerfile frontend/
          # Push the frontend Docker image to Docker Hub
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/$REPOSITORY:$IMAGE_TAG